config/routes.rb
Rails.application.routes.draw do
  resources :travels do 
    resources :car_pooling_requessts
  end
  resources :car_pooling_requessts
  resources :cities
  resources :users
  resources :notifications

end

app/models/car_pooling_requesst.rb
class CarPoolingRequesst < ActiveRecord::Base
	belongs_to :travel
	belongs_to :user

	validates :email, format: {with: /\w+@\w+\.com/}
	validates :password, presence: true
end

app/controllers/car_pooling_requessts_controller.rb
class CarPoolingRequesstsController < ApplicationController
  before_action :set_car_pooling_requesst, only: [:show, :edit, :update, :destroy]

  # GET /car_pooling_requessts
  # GET /car_pooling_requessts.json
  def index
    @car_pooling_requessts = CarPoolingRequesst.all
  end

  # GET /car_pooling_requessts/1
  # GET /car_pooling_requessts/1.json
  def show
  end

  # GET /car_pooling_requessts/new
  def new
    @car_pooling_requesst = CarPoolingRequesst.new
  end

  # GET /car_pooling_requessts/1/edit
  def edit
  end

  # POST /car_pooling_requessts
  # POST /car_pooling_requessts.json
  def create
    @car_pooling_requesst = CarPoolingRequesst.new(car_pooling_requesst_params)

    respond_to do |format|
      if @car_pooling_requesst.save
        format.html { redirect_to @car_pooling_requesst, notice: 'Car pooling requesst was successfully created.' }
        format.json { render :show, status: :created, location: @car_pooling_requesst }
      else
        format.html { render :new }
        format.json { render json: @car_pooling_requesst.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_pooling_requessts/1
  # PATCH/PUT /car_pooling_requessts/1.json
  def update
    respond_to do |format|
      if @car_pooling_requesst.update(car_pooling_requesst_params)
        format.html { redirect_to @car_pooling_requesst, notice: 'Car pooling requesst was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_pooling_requesst }
      else
        format.html { render :edit }
        format.json { render json: @car_pooling_requesst.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_pooling_requessts/1
  # DELETE /car_pooling_requessts/1.json
  def destroy
    @car_pooling_requesst.destroy
    respond_to do |format|
      format.html { redirect_to car_pooling_requessts_url, notice: 'Car pooling requesst was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_pooling_requesst
      @car_pooling_requesst = CarPoolingRequesst.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_pooling_requesst_params
      params.require(:car_pooling_requesst).permit(:email, :password, :user_id, :travel_id, :prefer_from, :prefer_to)
    end
end

app/helpers/car_pooling_requessts_helper.rb
module CarPoolingRequesstsHelper
end

app/views/car_pooling_requessts/_form.html.erb
<%= form_for(@car_pooling_requesst) do |f| %>
  <% if @car_pooling_requesst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_pooling_requesst.errors.count, "error") %> prohibited this car_pooling_requesst from being saved:</h2>

      <ul>
      <% @car_pooling_requesst.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :travel_id %><br>
    <%= f.number_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :prefer_from %><br>
    <%= f.text_field :prefer_from %>
  </div>
  <div class="field">
    <%= f.label :prefer_to %><br>
    <%= f.text_field :prefer_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_pooling_requessts/edit.html.erb
<h1>Editing Car Pooling Requesst</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_pooling_requesst %> |
<%= link_to 'Back', car_pooling_requessts_path %>

app/views/car_pooling_requessts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Car Pooling Requessts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>User</th>
      <th>Travel</th>
      <th>Prefer from</th>
      <th>Prefer to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_pooling_requessts.each do |car_pooling_requesst| %>
      <tr>
        <td><%= car_pooling_requesst.email %></td>
        <td><%= car_pooling_requesst.password %></td>
        <td><%= car_pooling_requesst.user_id %></td>
        <td><%= car_pooling_requesst.travel_id %></td>
        <td><%= car_pooling_requesst.prefer_from %></td>
        <td><%= car_pooling_requesst.prefer_to %></td>
        <td><%= link_to 'Show', car_pooling_requesst %></td>
        <td><%= link_to 'Edit', edit_car_pooling_requesst_path(car_pooling_requesst) %></td>
        <td><%= link_to 'Destroy', car_pooling_requesst, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car pooling requesst', new_travel_car_pooling_requesst_path %>

app/views/car_pooling_requessts/new.html.erb
<h1>New Car Pooling Requesst</h1>

<%= render 'form' %>

<%= link_to 'Back', car_pooling_requessts_path %>

app/views/car_pooling_requessts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @car_pooling_requesst.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @car_pooling_requesst.password %>
</p>

<p>
  <strong>User:</strong>
  <%= @car_pooling_requesst.user_id %>
</p>

<p>
  <strong>Travel:</strong>
  <%= @car_pooling_requesst.travel_id %>
</p>

<p>
  <strong>Prefer from:</strong>
  <%= @car_pooling_requesst.prefer_from %>
</p>

<p>
  <strong>Prefer to:</strong>
  <%= @car_pooling_requesst.prefer_to %>
</p>

<%= link_to 'Edit', edit_car_pooling_requesst_path(@car_pooling_requesst) %> |
<%= link_to 'Back', car_pooling_requessts_path %>